#!/usr/bin/env python2
# -*- coding: utf-8 -*-
#
# Banana banana banana.
#
# Dependencies : python-mpd
#                pysqlite

import os.path
import mpd
import random
import sqlite3
from time import sleep as sleep
from socket import error as socketerror

## Config
server="192.168.0.2"
port=6600
trigger=5  # A new song will be added when the playlist
           # has less songs than this
delay=0.5
dbfile="/tmp/autopl"
## End config

db = sqlite3.connect(dbfile)
cursor = db.cursor()

random.seed()
client = mpd.MPDClient()

## Functions

def reconnect(iter=0):
  print "Reconnecting"
  if iter==10:
    print "Connection lost"
    exit(1)
  try:
    client.connect(server, port)
  except socketerror:
    reconnect(iter+1)


def addsong():
  rand=random.uniform(-0.1, 1)
  cursor.execute("select * from songs where karma > ?", (karma,))
  data=cursor.fetchall()
  if data == None:
    addsong()
  else:
    songdata=random.choice(data)
    newkarma=karma(songdata, 2)
    cursor.execute("update songs set added=?, karma=? where file=?", (songdata[2]+1, newkarma, songdata[0],))
    db.commit()
    client.add(songdata[0])

def getsong(song):
  cursor.execute("select * from songs where file=?", (song,))
  data=cursor.fetchone()
  if data == None:
    cursor.execute("insert into songs values (?, 0, 0, 0.5)", (song,))
    data = (song, 0, 0)
  return data

def karma(songdata, which=0):
  listened=float(songdata[1])
  added=float(songdata[2])

  if which == 1:
    listened+=1
  elif which == 2:
    added+=1

  if listened==0:
    listened=0.01
  if added==0:
    added=0.01
  return listened/added

def listened(song):
  songdata=getsong(song)
  newkarma=karma(songdata, 1)
  cursor.execute("update songs set listened=?, karma=? where file=?", (songdata[1]+1, newkarma, song,))
  db.commit()

## End functions

try:
  client.connect(server, port)
except socketerror:
  reconnect()

## Startup
cursor.execute("create table if not exists songs(file text, listened int, added int, karma real);")
print "Verifying database..."
for song in client.list("file"):
  nothing=getsong(unicode(song))

db.commit()
print "Done"
armed=1

while True:
  while len(client.playlist()) < trigger:
    addsong()

  if not client.status()['state'] == "stop":
    time=client.status()['time'].split(":")
    pos=int(time[0])
    end=int(time[1])
    if armed==1 and (end > 15) and (pos > 3.0/4*end):
      armed=0
      listened(unicode(client.currentsong()["file"]))
      songid=(client.currentsong()["id"])

  if armed==0 and not songid == client.currentsong()["id"]: 
    armed=1
  
  sleep(delay)
