#!/bin/bash

bin="/usr/bin/autoplay"
runas="mpd"

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Autoplay"
    su $runas -c "$bin > /dev/null &>> 2>&1 &"
    stat_done
  ;;
  stop)
    stat_busy "Stopping Autoplay"
    su $runas -c "$bin kill > /dev/null 2>&1 &"
    pkill -fx "python2 $bin"
    stat_done
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  *)
    echo "usage: $0 {start|stop|restart}"
	;;
esac
exit 0

# vim: tw=70 ts=2 sw=2
