#!/bin/bash

bin="/usr/bin/autoplay"
runas="mpd"

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting Autoplay"
    su $runas -c "$bin > /dev/null &>> /tmp/autoplay.log &"
    stat_done
  ;;
  stop)
    stat_busy "Stopping Autoplay"
    pkill -fx "python2 $bin"
    stat_done
  ;;
  restart)
    $0 stop
    $0 start
  ;;
  update)
    if [[ $(pgrep -fx "python2 $bin") -ne 0 ]]
    then
      running=1
      $0 stop
    fi
    stat_busy "Updating Autoplay database"
    su $runas -c "$bin -u > /dev/null &>> /tmp/autoplay.log"
    stat_done
    if [[ $running -eq 1 ]]
    then
      $0 start
    fi
  ;;
  *)
    echo "usage: $0 {start|stop|restart|update}"
	;;
esac
exit 0

# vim: tw=70 ts=2 sw=2
